package com.hms;

import com.hms.domain.Patient;
import com.hms.software.DatabaseConnection;
import com.hms.software.PatientDAO;
import com.hms.software.PDFReportGenerator;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.*;
import java.net.InetSocketAddress;
import java.net.URLDecoder;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Server {

    public static void main(String[] args) throws Exception {
        // Start server on port 8080
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        
        // Define API Endpoints
        server.createContext("/api/patients", new PatientHandler());
        server.createContext("/api/reports", new ReportHandler());
        
        server.setExecutor(null); 
        server.start();
        System.out.println("✅ Backend Server started on http://localhost:8080");
        System.out.println("Keep this terminal running while using the website!");
    }

    // Handler for Patient Operations (GET and POST)
    static class PatientHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            // Allow CORS (Crucial for connecting HTML to Java)
            exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
            exchange.getResponseHeaders().set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
            exchange.getResponseHeaders().set("Access-Control-Allow-Headers", "Content-Type");

            if ("OPTIONS".equals(exchange.getRequestMethod())) {
                exchange.sendResponseHeaders(200, -1);
                return;
            }

            String method = exchange.getRequestMethod();
            PatientDAO dao = new PatientDAO();

            if ("GET".equals(method)) {
                // Fetch all patients and send as simple text/JSON-like format
                List<Patient> patients = dao.getAllPatients();
                StringBuilder response = new StringBuilder();
                response.append("[");
                for (int i = 0; i < patients.size(); i++) {
                    Patient p = patients.get(i);
                    response.append("{\"id\":").append(p.getPatId())
                            .append(",\"firstName\":\"").append(p.getFirstName()).append("\"")
                            .append(",\"lastName\":\"").append(p.getLastName()).append("\"")
                            .append(",\"phone\":\"").append(p.getPhone()).append("\"")
                            .append(",\"gender\":\"").append(p.getGender()).append("\"}");
                    if (i < patients.size() - 1) response.append(",");
                }
                response.append("]");
                
                byte[] bytes = response.toString().getBytes();
                exchange.sendResponseHeaders(200, bytes.length);
                exchange.getResponseBody().write(bytes);
                
            } else if ("POST".equals(method)) {
                // Add a new patient
                InputStream is = exchange.getRequestBody();
                String body = new String(is.readAllBytes());
                Map<String, String> params = parseFormData(body);
                
                Patient p = new Patient();
                p.setFirstName(params.get("firstName"));
                p.setLastName(params.get("lastName"));
                p.setDob(Date.valueOf(params.get("dob")));
                p.setGender(params.get("gender"));
                p.setBloodType(params.get("bloodType"));
                p.setPhone(params.get("phone"));
                p.setAddress(params.get("address"));
                
                boolean success = dao.addPatient(p);
                String response = success ? "{\"status\":\"success\"}" : "{\"status\":\"error\"}";
                
                byte[] bytes = response.getBytes();
                exchange.sendResponseHeaders(200, bytes.length);
                exchange.getResponseBody().write(bytes);
            }
            exchange.getResponseBody().close();
        }
    }

    // Handler for PDF Reports
    static class ReportHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
            
            PDFReportGenerator generator = new PDFReportGenerator();
            // Generate a sample PDF report
            boolean success = generator.generateSimpleReport("reports/test_report.pdf", "Hospital Report", "This is a test report generated by Java Backend.");
            
            String response = success ? "{\"status\":\"Report Generated\"}" : "{\"status\":\"Error\"}";
            byte[] bytes = response.getBytes();
            exchange.sendResponseHeaders(200, bytes.length);
            exchange.getResponseBody().write(bytes);
            exchange.getResponseBody().close();
        }
    }

    // Helper to parse HTML form data (e.g., firstName=John&lastName=Doe)
    private static Map<String, String> parseFormData(String body) throws UnsupportedEncodingException {
        Map<String, String> map = new HashMap<>();
        String[] pairs = body.split("&");
        for (String pair : pairs) {
            int idx = pair.indexOf("=");
            String key = URLDecoder.decode(pair.substring(0, idx), "UTF-8");
            String value = URLDecoder.decode(pair.substring(idx + 1), "UTF-8");
            map.put(key, value);
        }
        return map;
    }
}